spring:
  datasource:
    url: jdbc:postgresql://xxx:5432/huaweigps
    username: postgres
    password: xxx
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        temp:
          use_jdbc_metadata_defaults: false
server:
  port: 8001
webdriver:
  remote_webdriver_addr: http://192.168.1.3:4444
  local_proxy_ip: 192.168.1.10
huawei:
  username: xxx
  password: xxx
  phone_id: xxx